# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required
dist: trusty
bio_required: true
cache: packages

r:
 - release

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev

r_packages:
 - testthat
 - covr

bioc_packages:
 - xcms

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change
